# Generated by Django 3.2.5 on 2021-07-11 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=300)),
                ('code', models.CharField(help_text='Country code', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(help_text='Content from openweathermap API')),
                ('unix_last_update', models.DateTimeField(help_text='Unix by default')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(help_text='API location', srid=4326)),
            ],
            options={
                'ordering': ['-unix_last_update'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City name', max_length=300)),
                ('country', models.ForeignKey(help_text='Countries', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='weatherdashboard.country')),
                ('last_weather', models.ForeignKey(blank=True, help_text='Last weather reading', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='weatherdashboard.weather')),
            ],
        ),
    ]
